name: Release
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+rc[0-9]+'

jobs:
  check-sass:
    name: Check that Sass has been run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Install dependencies
        run: |
          npm install
          npm install -g sass

      - name: Run Sass
        run: grunt sass:dev

      - name: Check that the working directly is clean (no outstanding scss changes)
        run: git diff

  check-docs:
    name: Check that the docs compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install theme
        run: pip install -e .

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build docs
        run: make html
        working-directory: docs

  check-version-match:
    name: Check that library version matches tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install theme
        run: pip install -e .

      - name: Grab tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Check tag and version match
        run: |
          import pkg_resources
          version = pkg_resources.require("insegel")[0].version
          assert version == "${{ steps.vars.outputs.tag }}"
        shell: python

  publish-release:
    name: Publish release
    runs-on: ubuntu-latest
    needs: [check-sass, check-docs, check-version-match]
    steps:
      - uses: actions/checkout@v2

      - name: Build release
        run: python setup.py sdist bdist_wheel

      - name: Publish release to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
